CREATE DATABASE IF NOT EXISTS BankDB;

USE BankDB;

DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS SAVINGACCOUNT;
DROP TABLE IF EXISTS CURRENTACCOUNT;
DROP TABLE IF EXISTS OVERDRAFTLOAN;

CREATE TABLE CUSTOMER (
   	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   	SSN VARCHAR(45) NOT NULL,
	firstname VARCHAR(20) NOT NULL,	
	lastname VARCHAR(20) NOT NULL,	
	address VARCHAR(100) NOT NULL,	
	phone VARCHAR(20) NOT NULL,	
	email VARCHAR(30) NOT NULL,	
	username VARCHAR(15) NOT NULL,	
	userpassword VARCHAR(45) NOT NULL,	
	status enum('0','1') NOT NULL default '0',
	type enum('0','1') NOT NULL default '0',
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	create_at datetime,
	UNIQUE (SSN)
);

CREATE INDEX ssn_index ON CUSTOMER(SSN);
CREATE INDEX username_index ON CUSTOMER(username);
CREATE INDEX password_index ON CUSTOMER(userpassword);

CREATE TABLE SAVINGACCOUNT (
	accNo VARCHAR(20),
   	custID INT UNSIGNED ,
	amount DECIMAL(7,2),
	savingDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CURRENTACCOUNT (
	accNo VARCHAR(20),
   	custID INT UNSIGNED,
	amount DECIMAL(7,2),
	currentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE OVERDRAFTLOAN (
   	serialNo INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	curAccNo VARCHAR(20),
	amount DECIMAL(7,2),
	overdraftDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
